name: rickandmortyapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  marquee: ^2.2.3
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda-Black.ttf
        - asset: assets/fonts/Merienda-Bold.ttf
        - asset: assets/fonts/Merienda-ExtraBold.ttf
        - asset: assets/fonts/Merienda-Light.ttf
        - asset: assets/fonts/Merienda-Medium.ttf
        - asset: assets/fonts/Merienda-Regular.ttf
        - asset: assets/fonts/Merienda-SemiBold.ttf
  
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
